### PR TITLE
Fix discrepancy between TypeScript definition and acutal module export

### LINKED ISSUE #5: Getting Webpack error on "new Graph() in ts file
I'm getting a web pack error when trying to use with an Angular application:

```
TypeError: tarjan_graph__WEBPACK_IMPORTED_MODULE_7__.Graph is not a constructor
```

My code is:

```
import { Graph } from 'tarjan-graph';

createTarganGraph(topics: Topic[]): Graph {
        const graph = new Graph();
        topics.forEach(t => graph.add(t.name, t.prereqs.map(p => p.topic_name)));
        return graph;
    }
```

Any ideas what I might be doing wrong?

Thanks

### PR DESCRIPTION
**Pull request by mrkev**
Fixes #5 to allow `Graph` to be properly imported on TypeScript projects

### CODE REVIEW

**Comment by ChristopherChudzicki** [comment]
@mrkev I just ran into this issue, too. Thanks for the PR pointing out the discrepancy.

It might be better to fix the typings rather than the change the export, though. This PR would be a breaking change.

For others stumbling here... to monkey patch the types so they accurately reflect the tarjan-graph library:

```ts
declare module "tarjan-graph" {
  interface Vertex {
    name: string;
    successors: Vertex[];
    index: number;
    lowLink: number;
    onStack: boolean;
    visited: boolean;
    reset: () => void;
  }

  export default class Graph {
    vertices: { [key: string]: Vertex };
    add(key: string, descendants: string[] | string): Graph;
    reset(): void;
    addAndVerify(key: string, descendants: string[] | string): Graph;
    dfs(key: string, visitor: (v: Vertex) => void): void;
    getDescendants(key: string): string[];
    hasCycle(): boolean;
    getStronglyConnectedComponents(): Vertex[][];
    getCycles(): Vertex[][];
    clone(): Graph;
    toDot(): string;
  }
}
```

**Comment by tmont** [comment]
Hi. Thanks for the PR and the comments about how terribly lazy I've been with the TypeScript stuff. I decided to just port the whole thing to TypeScript and emit the declaration that way instead of (poorly) handcrafting it. This should fix all problems with the code not matching the declarations. Sorry about that.

The updated module is in NPM at `tarjan-graph@3.0.0`. Note that this is in fact a breaking change as I changed the default export as both of you noticed. So now your code should be like:

```typescript
const Graph = require('tarjan-graph').default; // js
import Graph from 'tarjan-graph'; // ts
```

**Comment by mrkev** [comment]
Hey sorry just saw this. haha you're right, changing the definition would've been better @ChristopherChudzicki. In any case thanks for figuring this out @tmont 👍

**Comment by ChristopherChudzicki** [comment]
Thanks, @tmont!

**Pull request closed without merging**
